### ISSUE TITLE
Perhaps show ~30 stations by default or so

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/rubio-radio#10]
Just a quick idea: perhaps add a few more radio stations on default. I think I had about 12-15 entries or so.
I think having 20-25 by default e. g. --count 25 or something may be better than whatever the current 
way is. Also perhaps we can support a fancy option such as "--world-languages" or something where
one radio station per language is added. :D (Does not have to include ALL languages per se but I
was just thinking this could be fun, since we have had german, english, hindi and so forth right now.
Misses one japanese radio station... do japanese folks have something like BBC, but in japanese
rather than english? Here in Europe BBC is quite popular, more popular than US radio stations)

**Comment by AndyObtiva** [comment]
> Just a quick idea: perhaps add a few more radio stations on default. I think I had about 12-15 entries or so.
> I think having 20-25 by default e. g. --count 25 or something may be better than whatever the current
> way is

I think you have a misunderstanding of how the app operates. It pulls in 10,000 radio stations by default, not 12-15.

However, it shows 20 stations per page by default, so you have to click the `>` button (Next button) to see more stations or enter the page number into the number entry.

In any case, if you run it with `--count 25`, you will only get 25 stations with pagination, which is less than the default and very very little. 

What you might be really looking for it the `--per-page` option.

Set it to `--per-page 30` to see 30 stations at a time instead of 20 (default).

> Also perhaps we can support a fancy option such as "--world-languages" or something where
> one radio station per language is added. 

Languages are already supported. You just have to enter the right language into the filter to find it (you can find Japanese, German, French, English, Spanish, Portuguese, etc...)

<img width="740" alt="Screen Shot 2022-08-16 at 11 31 38 AM" src="https://user-images.githubusercontent.com/23052/184921910-fe423ee2-dee6-4bb4-a318-8487efd783b0.png">

**Comment by AndyObtiva** [comment]
@rubyFeedback Please include a screenshot of your Windows rubio-radio app. I want to see if it is loading and paginating radio stations correctly. Thanks in advance.

**Comment by AndyObtiva** [comment]
I am closing this because I do not believe it is a real issue, yet a misunderstanding of how rubio-radio works. Also, because I did not hear back from the issue author.
