### ISSUE TITLE
Check for incorrect backends

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/rubio-radio#11]
Hey there kojix2 and Andy,

Following my tests yesterday on windows I tried today to see whether mpv as backend
is supported (on linux actually). I think it is not.

It should be quite simple to support e. g.

    https://shapeshed.com/listening-to-bbc-radio-with-mpv/
    https://shapeshed.com/listening-to-bbc-radio-with-mpv/

Anyway - this is actually not the reason for the issue report here.

Just for the sake of it, I tested the following

    ruby rubio  --backend mpveegge

So a bogus variant for --backend.

My proposal:

- Would it be possible to specify the allowed backends, and if the input (such as
mpveegge in this case) is NOT found as allowed backend, to notify the user
about it, and perhaps explain that as backend vlc will be used instead?

Also I think it may be useful to add an additional entry in the menu interface
to indicate which backend is currently used. Perhaps an additional message
popup showing this like:

    backend in use: vlc

and, if possible and you want to go fancy, to perhaps also toggle this in the
menu or some other interface. Something like "configuration" options or
something like that.

Anway, I like how much you can do with a minimalistic radio. Now let's hope
libui-ng can add tons more cross-platform goodies eventually  ... :D

Edit: Ah yes, also ... right now I have not vlc installed on linux. So perhaps
the command should be checked whether vlc exists or not before it tries
to play it. This actually led to a crash on my linux box but I will add a 
separate issue. This may be more related to the glimmer code actually
so perhaps Andy may have a look at it, but you'll understand this in
the other issue request.

**Comment by AndyObtiva** [comment]
No, because the whole point of keeping backend support open is to support even future platforms or unknown platforms that can stream/play radio by simply passing in a URL. This makes rubio-radio more compatible with a lot more backends, without even knowing about them.

As such, I don't recommend implementing any validation. It's OK if it fails on incompatible backends. That's on the consumer to handle properly.

By the way, here are 3 ways to install VLC on Linux that might make your life easier.

https://www.vlchelp.com/install-ubuntu-linux/#:~:text=Search%20for%20and%20launch%20Terminal,be%20downloaded%20and%20installed%20automatically.

**Comment by kojix2** [comment]
Hi, shevy.

 I just tried `rubio --backend mpv` on Ubuntu. It seems to work well. I think `--backend` option should be open to accepting future or unknown backends. Thanks to that, I didn't know about mpv until now, but I'm calling mpv with rubio. Andy explains this in more precise English above.

But let's think for a moment about implementing validation.

First, it is impossible to list the players available on the local computer. (When someone places a player named `excel.exe` in the path, it would be challenging to determine that it is, in fact a media player.)

Second, consider checking to see if a player's command line tools are available.

In the bioinformatics field, people create workflows and use a combination of Unix tools. Shell scripts, Perl, and workflow languages. My favorite is [nextflow](https://www.nextflow.io), but it seems that there are many [CWL](https://www.commonwl.org) enthusiasts in Japan. But this is not the time to talk about this. The `which` command is usually used to determine if the tool is available. (You may know this because you published a gem called biorobe and probably did some work related to bioinformatics.)

For example,  [d-cameron](https://github.com/d-cameron), a famous Australian bioinformatician, wrote the following code (slightly modified):

```sh
write_status() {
	echo "$(date): $1" 1>&2
}

for tool in samtools bcftools gunzip tar rsync wget ; do
	if ! which $tool >/dev/null; then
		echo "Error: unable to find $tool on \$PATH" 1>&2
		exit
	fi
	write_status "Found $(which $tool)"
done
```

The `which` command is not available on Windows, so it seems that you need to use something called `where.exe` instead. 

This way we would be able to see if command line tools are available. However, I am not confident about Windows compatibility. 

If you are interested, please send me a pull request.

**Comment by AndyObtiva** [comment]
I am closing this because: 
- We provided a solution for making `mpv` work
- We indicated we could not really validate backends
- The user could always create an adapter-script (shell script, Ruby script, or any kind of script) that could adapt any player's command to work by receiving a URL as expected by the rubio-radio `backend` option (e.g. assuming `playerxyz` does not work by accepting URL directly yet by passing `--url=URL`, you could create a `rubio-playerxyz` script that could accept URL directly and invoke `playerxyz` correctly with it).

Also, if the issue author wants to submit a pull request with enhancements to the `backend` option, they are free to do so outside of this issue.
