### ISSUE TITLE
Background for rubio-radio

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/rubio-radio#4]
Heya kojix2,

I just found the project indirectly, by Andy who linked in to it (or, rather than linked in, I found it by looking at Andy's github page, and then found the project here).

If you have the time and motivation, could you add a **short** rationale or background why you created this project? I assume it was because you wanted to test glimmer-libui, possibly, but I am not sure. So just a sentence or two should suffice, to understand why the project was created.

Thanks for reading this.

**Comment by AndyObtiva** [comment]
@rubyFeedback The rationale behind creating a Radio desktop app is obvious. It's to get access to radio stations quickly via a desktop app instead of having to navigate through a web browser to radio websites. I've been using the radio app too for Jazz, Metal, Indie Rock, and Electronic House music. Check out the "Metallica & Iron Madien ONLY" radio station if you like Metal music. It's pretty good!

**Comment by kojix2** [comment]
Hello.

I wanted to learn to listen to English better, and I thought YouTube is good, but radio is also good. Because radio programs are audio from the beginning.

I use Ubuntu desktop at home.
I looked around and found a nifty app like [shortwave](https://apps.gnome.org/app/de.haeckerfelix.Shortwave/).
I noticed RadioBrowser because shortwave was using RadioBrowser.
But I thought a smaller, simpler app would be better. So I actually made it.

There are probably more sophisticated radio apps if you look for them. 
There is a plugin that adds a radio browser to Rhythmbox (Ubuntu's default media player). 
But isn't it fun to write your own scripts?

I use Glimmer because it was much easier to write in Glimmer. (And I knew I would never package this script on Windows.) Not because I wanted to test Glimmer.

Rationale? There's no unique feature that you can't do without Rubio Radio. There's a huge VLC running in the background. All Rubio has to do is give the VLC a letter of request, and the VLC will do all the work. That's it.  But it works fine. I can listen to the radio. It is working. It's listening.
