### ISSUE TITLE
Feedback for rubio-radio and a few suggestions

### ISSUE THREAD

**Issue by rubyFeedback** [kojix2/rubio-radio#9]
Today I finally had some time to test rubio-radio on windows.

I followed kojix2' official instructions.

First I installed VLC. Worked fine.

Then I added to PATH, this also worked. I tested via cmd.exe
and I could start vlc from the commandline afterwards.

Next I did gem install rubio-radio. This worked fine too.
(I had to interrupt it once because documentation installation
was hanging but this is a rubygems problem I think. After
I interrupted it and did it anew, it worked fine.)

Then I did "rubio" and it started.

I could see about 12 or so entries. I clicked on one randomly
on the > Play button and it started to play the radio after
perhaps 2 seconds or so. \o/

So this works fine.

I think kojix2 never intended this to be a fully fledged radio
player GUI, so please skip any recommendations to come
next.

So in no particular order:

(1) Could you add one japanese radio station by default? :D

(2) Would it be possible to add a menu entry "fetch
tons of radio stations"? I could only see like the 12
and no way to add more.

(3) Would it be possible to add/remove entries, and
perhaps add a menu entry export into yaml and json
format? And perhaps load from these? That way users
could define their own bookmarks from within the GUI,
and perhaps load from the commandline like

    rubio --config-file=foobar.yml # or something like that, I did not check whether this is possible already or not

**Comment by AndyObtiva** [comment]
> (1) Could you add one japanese radio station by default? :D

This is already supported. The list of radio stations does include Japanese stations. You just have to enter "japanese" in the filter above the table of stations, and you will see Japanese radio stations.

<img width="740" alt="Screen Shot 2022-08-16 at 11 31 38 AM" src="https://user-images.githubusercontent.com/23052/184919693-3709835b-c169-49c5-a760-58407ff664a4.png">

**Comment by AndyObtiva** [comment]
> (2) Would it be possible to add a menu entry "fetch
> tons of radio stations"? I could only see like the 12
> and no way to add more.

This is already supported too. The app pulls in 10,000 radio stations by default, but they are paginated for user-friendliness (you see 20 per page). You just have to click the `>` button (i.e. the Next button) to see more, or otherwise enter the page number you want in the number text field.

<img width="740" alt="Screen Shot 2022-08-16 at 11 34 38 AM" src="https://user-images.githubusercontent.com/23052/184920079-7a7e88da-4db3-416b-bcf4-f5d31d0c66ee.png">

<img width="740" alt="Screen Shot 2022-08-16 at 11 36 05 AM" src="https://user-images.githubusercontent.com/23052/184920382-7b5a70ec-63a3-4f8f-9e0f-680bfe27b495.png">

**Comment by AndyObtiva** [comment]
> (3) Would it be possible to add/remove entries, and
> perhaps add a menu entry export into yaml and json
> format? And perhaps load from these? That way users
> could define their own bookmarks from within the GUI,
> and perhaps load from the commandline like

This is also already supported in the latest version of rubio-radio, which was just released yesterday. You can simply "star" any stations you like (i.e. bookmark them), and then later check them out in the View menu -> Bookmarks.

![bookmarks](https://raw.githubusercontent.com/kojix2/rubio-radio/main/screenshots/rubio-radio-mac-example-view-bookmarks.png)

Bookmarks get stored under `~/.rubio-radio/bookmarks.yml`

I do not see value in allowing the user to customize the storage location at this time.

**Comment by kojix2** [comment]
@rubyFeedback 
Uploading code to Github or Gitlab is far more important than the Rubyio spec. 
(The feature Andy mentioned is already implemented.)

The RubyGem server has a large number of RubyGems that you have created. 
https://rubygems.org/profiles/shevy
However, these gems are not well known and few people use them. I think this is simply because they are placed in places where the code is hard to see.

This is because the RubyGem server is usually nothing more than a computer warehouse, not suitable for humans to read and think about the source code. The actual number of lines of code produced is staggering. But it is not easy to get the full picture.

To me, your mysterious behavior makes you look like a great outsider artist.

But many outsider artists go undiscovered. Only a small percentage are recognized for their value after death, and most disappear into the darkness of history without being discovered by anyone. Outsider artists, however, can become real artists if someone understands them.

That's why it's important to upload your work to Github or Gitlab.
Because it could change your life....

Translated with www.DeepL.com/Translator (free version)
